security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

    access_control:
        - { path: ^/pin/create, roles: ROLE_USER }
        - { path: ^/pin/\d+/edit, roles: ROLE_USER }
        - { path: ^/pin/\d+/delete, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/pin, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
